#pragma once

#include <string>
#include <string_view>

class LoggedUser final
{
public:
    /*######################################
    ############# CONSTRUCTORS #############
    ######################################*/

    LoggedUser() = delete;
    explicit LoggedUser(const std::string& username);

    /*######################################
    ############ PUBLIC METHODS ############
    ######################################*/

    const std::string& getUsername() const noexcept;

    /*######################################
    ######### OPERATORS OVERLOADING ########
    ######################################*/

    // Normal operator== is automatically generated by the compiler to avoid boilerplate code
    bool operator==(const LoggedUser& other) const noexcept = default;
    bool operator==(std::string_view otherUsername) const noexcept;

private:
    /*######################################
    ################ MEMBERS ###############
    ######################################*/

    std::string m_username;
};
